# Generated by Django 5.0.3 on 2025-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=255)),
                ('year_of_passing', models.CharField(blank=True, max_length=10, null=True)),
                ('assignment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proctored_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_numeric', models.IntegerField(blank=True, null=True)),
                ('grade_letter', models.CharField(blank=True, max_length=5, null=True)),
                ('timeline', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
