# Generated by Django 5.0.3 on 2025-04-19 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_certificate_proctored_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='assignment_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='college_roll_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credit_transfer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credits_mriirs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='eligible_for_modified_pass',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='final_exam_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='grade_letter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='grade_numeric',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='proctored_exam_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='sem',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='study_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='timeline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='week',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='year_of_passing',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
